# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: restaurant.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'restaurant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10restaurant.proto\x12\nrestaurant\"\x98\x01\n\nRestaurant\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x0e\n\x06rating\x18\x05 \x01(\x01\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\x12\x11\n\tis_active\x18\x08 \x01(\x08\"-\n\x14GetRestaurantRequest\x12\x15\n\rrestaurant_id\x18\x01 \x01(\t\"C\n\x15GetRestaurantResponse\x12*\n\nrestaurant\x18\x01 \x01(\x0b\x32\x16.restaurant.Restaurant2i\n\x11RestaurantService\x12T\n\rGetRestaurant\x12 .restaurant.GetRestaurantRequest\x1a!.restaurant.GetRestaurantResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'restaurant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESTAURANT']._serialized_start=33
  _globals['_RESTAURANT']._serialized_end=185
  _globals['_GETRESTAURANTREQUEST']._serialized_start=187
  _globals['_GETRESTAURANTREQUEST']._serialized_end=232
  _globals['_GETRESTAURANTRESPONSE']._serialized_start=234
  _globals['_GETRESTAURANTRESPONSE']._serialized_end=301
  _globals['_RESTAURANTSERVICE']._serialized_start=303
  _globals['_RESTAURANTSERVICE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
